apiVersion: v1
kind: Service
metadata:
  name: openvpn-db
  namespace: vpn
spec:
  type: NodePort
  selector:
    app: openvpn-db
  ports:
    - name: openvpn-tcp
      port: 1194
      targetPort: 1194
      protocol: TCP
      nodePort: 31194
