apiVersion: v1
kind: Secret
metadata:
  name: openvpn-monitoring-config
  namespace: vpn
type: Opaque
stringData:

  server-tcp.conf: |
    port 1195
    proto tcp
    dev tun

    topology subnet
    server 10.89.0.0 255.255.255.0
    ifconfig-pool-persist /tmp/ipp.txt

    ca /etc/openvpn/ca.crt
    cert /etc/openvpn/server.crt
    key /etc/openvpn/server.key
    dh /etc/openvpn/dh.pem

    tls-crypt /etc/openvpn/ta.key
    crl-verify /etc/openvpn/crl.pem

    keepalive 10 120
    persist-key
    persist-tun

    user nobody
    group nogroup

    auth SHA256
    cipher AES-256-CBC
    ncp-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
    tls-version-min 1.2

    push "route 10.233.0.0 255.255.192.0"
    push "route 10.233.64.0 255.255.192.0"
    push "route <MONITORING_CLIENT_NETWORK> <SUBNET_MASK>"

    push "dhcp-option DNS 10.233.0.3"
    push "dhcp-option DOMAIN cluster.local"

    verb 3
    status /tmp/openvpn-status.log
    log-append /dev/stdout

  ca.crt: |
    <CA_CERT>

  server.crt: |
    <SERVER_CERT>

  server.key: |
    <SERVER_KEY>

  dh.pem: |
    <DH_PARAMS>

  crl.pem: |
    <CRL>

  ta.key: |
    <TA_KEY>
